version: '3.1'
services:
  prometheus:
    build:
      context: .
      dockerfile: ./etc/docker/prometheus/dockerfile
    container_name: "prometheus"
    hostname: "prometheus"
    ports:
      - "9090:9090"

  grafana:
    build:
      context: .
      dockerfile: ./etc/docker/grafana/dockerfile
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
#
