server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  shutdown: graceful
  error:
    include-exception: off
    include-stacktrace: never
    include-message: never

spring:
  profiles:
    active: default
  config:
    import:
      - classpath:config/common.yaml


  jackson:
    time-zone: CET
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      
  security:
    user:
      roles: ACTUATOR

  data:
    mongodb:
      database: axon-tasks-db
      auto-index-creation: true




axon:
  aggregate:
    snapshotThreshold: 500

  ### enable dimensional metrics
  metrics:
    micrometer:
      dimensional: true
---
spring:
  config:
    activate:
      on-profile: development

---
spring:
  config:
    activate:
      on-profile: integration
---
spring:
  config:
    activate:
      on-profile: preproduction
---
spring:
  config:
    activate:
      on-profile: production
