spring:
  sleuth:
    baggage:
      remote-fields: trid
      correlation-fields: trid


  messages:
    fallback-to-system-locale: false

logging:
  level:
    root: WARN
    ch.keepcalm.security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:-},%X{onlineId:-},%X{trid:-},%X{traceId:-},%X{spanId:-},%X{spanExportable:-}]'
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} - %clr(${spring.application.name:-}){green} - %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"


management:
  endpoints:
    web:
      exposure:
          include: "prometheus,health,info,metrics"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      app: ${spring.application.name}

keepcalm:
  security:
    endpoints:
      unsecured:
        - "/**"
