apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rule.yaml

configurations:
  - params.yaml

vars:
  - name: name
    objref:
      kind: PrometheusRule
      name: app
      apiVersion: monitoring.coreos.com/v1
    fieldref:
      fieldpath: metadata.labels.app
  - name: namespace
    objref:
      kind: PrometheusRule
      name: app
      apiVersion: monitoring.coreos.com/v1
    fieldref:
      fieldpath: metadata.namespace
