spring:
  # MongoDB
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PASSWORD}@mongodb-0.mongodb-headless.demo.svc.cluster.local:27017,mongodb-1.mongodb-headless.demo.svc.cluster.local:27017
  redis:
    host: redis-master
    port: 6379
    password: ${REDIS_PASSWORD}
