global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spring-actuator
    honor_timestamps: true
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 192.168.1.101:8080
          - 10.44.66.16:8080
