{
 "title": "Axon Framework Application",
 "description": "Dashboard for Axon Framework Application (micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(app)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{app=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Axon Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Commands",
   "type": "singlestat",
   "description": "Total number of success commands",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "description": "Total number of failed commands",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Processed Commands",
   "type": "singlestat",
   "description": "Total number of processed\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ingested Commands",
   "type": "singlestat",
   "description": "Total number of ingested\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ignored Commands",
   "type": "singlestat",
   "description": "Total number of ignored\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Commands Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Success commands"
    },
    {
     "expr": "sum(irate(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Failed commands"
    },
    {
     "expr": "sum(irate(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Processed commands"
    },
    {
     "expr": "sum(irate(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ingested commands"
    },
    {
     "expr": "sum(irate(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ignored commands"
    }
   ]
  },
  {
   "title": "Command Bus Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(commandBus_capacity{app=\"$application\", instance=~\"$instance\"}) by (app)",
     "legendFormat": "Command bus"
    }
   ]
  },
  {
   "title": "Command Bus Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  },
  { "title": "Axon Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Success Events",
   "type": "singlestat",
   "description": "Total number of success events",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "description": "Total number of failed events",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "singlestat",
   "description": "Total number of processed\n events",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Events",
   "type": "singlestat",
   "description": "Total number of ingested\n events",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Events",
   "type": "singlestat",
   "description": "Total number of ignored\n events",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Events Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success events"
    },
    {
     "expr": "sum(irate(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed events"
    },
    {
     "expr": "sum(irate(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed events"
    },
    {
     "expr": "sum(irate(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested events"
    },
    {
     "expr": "sum(irate(eventStore_ignoredCounter_total{app=\"$application\", instance=\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored events"
    }
   ]
  },
  {
   "title": "Event Bus Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  },
  { "title": "Axon Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Success Queries",
   "type": "singlestat",
   "description": "Total number of success queries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "singlestat",
   "description": "Total number of failed queries",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "singlestat",
   "description": "Total number of processed\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Queeries",
   "type": "singlestat",
   "description": "Total number of ingested\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Queries",
   "type": "singlestat",
   "description": "Total number of ignored\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Queries Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success queries"
    },
    {
     "expr": "sum(irate(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed queries"
    },
    {
     "expr": "sum(irate(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed queries"
    },
    {
     "expr": "sum(irate(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested queries"
    },
    {
     "expr": "sum(irate(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored queries"
    }
   ]
  },
  {
   "title": "Query Bus Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queryBus_capacity{app=\"$application\", instance=~\"$instance\"})by(app)",
     "legendFormat": "Query bus"
    }
   ]
  },
  {
   "title": "Query Bus Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  }
 ]
}