apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: c3smonkey/template
          name: kboot-tasks
          ports:
            - containerPort: 8080
              name: 8080-tcp
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      restartPolicy: Always
