apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: kboot-tasks
          env:
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-encrypt
                  key: key
